name: Build and Deploy to Azure Web App using Azure CLI

on:
  push:
    branches:
      - frontend-prod
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install dependencies and build the application
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Step 4: Zip the build directory
      - name: Zip build artifacts
        run: |
          cd build
          zip -r ../build.zip ./
          cd ..

      # Step 5: Login to Azure CLI
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 6: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        run: |
          az webapp deploy \
            --resource-group ZBConverter \
            --name zb-frontend \
            --src-path build.zip \
            --type zip
